### ISSUE TITLE
Create a web page

### ISSUE THREAD

**Issue by TheLethalCode** [TheLethalCode/Artemis-arrow#1]
Design and create a web page that will act as the front end for the app.

**Comment by UmangGPatel** [comment]
Hi there I am Umang From KWoC 2018 I show your project and there is issue that create a web app for your application so my question is what kind of web app do you want and in which technology

**Comment by TheLethalCode** [comment]
@UmangGPatel this issue is regarding the creation of a web page. The web app is the focus of the entire project. I would request you to join the project communication channel, provided in the project description in the Kwoc page for further details.

**Comment by robonetphy** [comment]
so can you give me some idea about view of webpages
