### ISSUE TITLE
Bugs in Youtube downloader

### ISSUE THREAD

**Issue by TheLethalCode** [TheLethalCode/Artemis-arrow#3]
Right now, for the songs downloading part, we are getting the link for the Youtube video of the song and downloading it from an external youtube converter. If we are not able to convert the video, we use youtube dl library. It would be best if we entirely use youtube dl as it is foolproof.

**Comment by prashantramnani** [comment]
Is it fixed?
And what is authentication? I suppose that's a file, but it's not there
![screenshot from 2018-12-13 07-58-46](https://user-images.githubusercontent.com/32036551/49911729-79bc9700-fead-11e8-83cb-4b704bfd4e2f.png)

**Comment by prashantramnani** [comment]
@TheLethalCode  ??

**Comment by TheLethalCode** [comment]
Ho well, I deleted the authentication file, you should be able to find it in the master branch. See if you can make the song downloader working

**Comment by prashantramnani** [comment]
How do you plan to make this thing. It's working, the youtube-dl is working fine and the youtube playlist thing is also, it can read from songs.txt, download the songs and add them to the youtube playlist. What exactly am I supposed to do?

**Comment by TheLethalCode** [comment]
If it's downloading all right, then fine. When I tried, it gave some credential error!

**Comment by prashantramnani** [comment]
umm..so that's it? any idea how to improve it? I can work in this, if you have any ideas?

**Comment by TheLethalCode** [comment]
I actually dont think it is complete. Don't take auth file from the master branch. There is a reason I deleted it from the devel. Rewrite it using requests and integrate it with the main flask app.

**Comment by prashantramnani** [comment]
What was the reason that you had to delete that file? Anyway I'll write it again.

**Comment by TheLethalCode** [comment]
The previous file, creates a temporary server and opens the user's browser.
Since we have a server running we don't need that and we don't want the
local server's browser being opened.
