### ISSUE TITLE
suggestions for improvement by adding a few features

### ISSUE THREAD

**Issue by Shankusu7** [TheLethalCode/Artemis-arrow#7]
following suggestions:
1)Anime feature should support requests for downloading an anime  both sub and dub versions.

2)the app should have a "report missing anime/book/song" feature.

3) what if a request come for downloading copyright restricted content?(or a content which is not avalible on the internet for download)

**Comment by TheLethalCode** [comment]
@Shankusu7 yep, sub and dub will be treated as two different anime. And your point 3), is just basic error handling. We will take care of it, it need not be a separate feature. Closing issue
