### ISSUE TITLE
Piracy issues?

### ISSUE THREAD

**Issue by amansheaven** [TheLethalCode/Artemis-arrow#8]
I am quite interested in this app and I know some sources which can lead us to delivering the app but If we let them download for free it would be pirated that won't be allowed?

**Comment by TheLethalCode** [comment]
@amansheaven If the source itself is not copyrighted, it won't be a piracy issue. And moreover this is a logistic issue,  and we will take care of it, when we launch it :) . For now, I am closing the issue.
